# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

steps:
- script: echo Beginning JMeter Sample Build
  displayName: 'Build and Load Test a .Net Core App'

- script: |
  displayName: 'Build and Test'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    clean: true

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'

- task: CmdLine@2
  inputs:
    script: 'C:\apache-jmeter-5.2.1\bin\jmeter -n -t c:\temp\test-scenario.jmx -l c:\temp\TfsJmeterResults.csv'